DROP TABLE IF EXISTS Persona;

create table condiciones (id integer generated by default as identity, cuotamax integer, cuotamin integer, diapago integer, tea double, tarjeta_id integer, primary key (id));
create table persona (id integer generated by default as identity, nombre varchar(255), primary key (id));
create table tarjeta (id integer generated by default as identity, nombre varchar(255), primary key (id));
alter table condiciones add constraint FKls67ondys0gxpnjvo8qx97dh9 foreign key (tarjeta_id) references tarjeta;
